name: learn1
# Run on a push to the deploy branch
on: 
  push:
    branches:
        - deploy
        
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Echo secret key
        env: 
          mname : ${{secrets.MY_NAME}}
        run: node test.js
